# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(375, 500)
        MainWindow.setMinimumSize(QtCore.QSize(375, 500))
        MainWindow.setMaximumSize(QtCore.QSize(375, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logorat/images/favicon-blackrat.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(17, 17, 17);\n"
"color: rgb(255, 255, 255);R")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(12, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_funcoes = QtWidgets.QFrame(self.centralwidget)
        self.frame_funcoes.setMaximumSize(QtCore.QSize(350, 450))
        self.frame_funcoes.setStyleSheet("")
        self.frame_funcoes.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_funcoes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_funcoes.setObjectName("frame_funcoes")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_funcoes)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_funcoes2 = QtWidgets.QFrame(self.frame_funcoes)
        self.frame_funcoes2.setMaximumSize(QtCore.QSize(302, 16777215))
        self.frame_funcoes2.setStyleSheet("")
        self.frame_funcoes2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_funcoes2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_funcoes2.setObjectName("frame_funcoes2")
        self.frame_logo = QtWidgets.QFrame(self.frame_funcoes2)
        self.frame_logo.setGeometry(QtCore.QRect(0, 60, 302, 91))
        self.frame_logo.setMinimumSize(QtCore.QSize(302, 0))
        self.frame_logo.setMaximumSize(QtCore.QSize(302, 16777215))
        self.frame_logo.setStyleSheet("background-image: url(:/logorat/images/logo-blackrat.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;")
        self.frame_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_logo.setObjectName("frame_logo")
        self.label_select_login = QtWidgets.QLabel(self.frame_funcoes2)
        self.label_select_login.setGeometry(QtCore.QRect(100, 160, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_select_login.setFont(font)
        self.label_select_login.setStyleSheet("")
        self.label_select_login.setObjectName("label_select_login")
        self.QPushButton_login = QtWidgets.QPushButton(self.frame_funcoes2)
        self.QPushButton_login.setGeometry(QtCore.QRect(100, 200, 101, 121))
        self.QPushButton_login.setStyleSheet("QPushButton {\n"
"    background-image: url(:/logorat/images/flask-login.png);\n"
"    background-position:center;\n"
"    background-repeat: no-repeat;\n"
"    border-radius:50px;\n"
"    background-color: rgb(35, 35, 35);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"    border: 2px solid rgb(170, 255, 0);\n"
"}")
        self.QPushButton_login.setText("")
        self.QPushButton_login.setIconSize(QtCore.QSize(20, 20))
        self.QPushButton_login.setObjectName("QPushButton_login")
        self.label_flask_master = QtWidgets.QLabel(self.frame_funcoes2)
        self.label_flask_master.setGeometry(QtCore.QRect(110, 330, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_flask_master.setFont(font)
        self.label_flask_master.setStyleSheet("")
        self.label_flask_master.setObjectName("label_flask_master")
        self.horizontalLayout.addWidget(self.frame_funcoes2)
        self.verticalLayout.addWidget(self.frame_funcoes)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Black Rat"))
        self.label_select_login.setText(_translate("MainWindow", "Select function"))
        self.label_flask_master.setText(_translate("MainWindow", "Flask Master"))
import file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
